### ISSUE TITLE
negotiationFormatter is null when LinqToQuerystring returns a Dictionary

### ISSUE THREAD

**Issue by qwertoyo** [Roysvork/LinqToQuerystring#39]
Hi @Roysvork , and thanks for your work.

I'm not sure this is a issue of your package or in my configuration, let's see: I have a js component which uses "advanced" OData features that are not supported directly on webApi 2, so your component was a nice discovery.

I currently have a problem that I can't solve at the moment: when the LinqToQuerystring method called at line 35 in LinqToQueryableAttribute.cs returns a Dictionary<String, Object>, the conneg.Negotiate @ line 47 always returns null (and then 500). 

Is some kind of bug or (prolly) I just need to extend/add some serializer in the configuration.Formatters?

Thanks,
Antonio

**Comment by Roysvork** [comment]
Closing for now, happy to reopen if we receive a reproduction.
