### ISSUE TITLE
startswith() should use regex for querying

### ISSUE THREAD

**Issue by stanislavromanov** [Roysvork/LinqToQuerystring#46]
Hello, I did some tests and found out that `startswith()` is not using regex but should since then it can take into account indexes.

For example I have table with 30 million random documents, they have property `Name` which is indexed.

`?$filter=startswith([Name],'abc') eq true` takes 36 seconds

`.find({Name : /^abc/})` takes 0 seconds

Can we make sure that whenever we use `startswith()` it'll always use regex?

**Comment by Roysvork** [comment]
Hi there,

What linq provider are you using? Linq to querysting does not perform any function other than creating an expression tree that is then used by the provider to create a query. It may be that there is some quick win here but it sounds like it may be a limitation of your provider itself.

Pete

**Comment by stanislavromanov** [comment]
I think the problem is inside the actual MongoDb Driver. Sorry for misunderstanding. :)
